= Minimal podman slurm configuration

== Description

This project contains a minimal slurm configuration and a Dockerfile that can be used to run a docker container using podman via slurm.

== Usage

To use this project, first, clone the repository and the get/build the podman image:

1. Clone this repository

    cd ~/projects
    git clone https://github.com/LuKrO2011/podman-slurm-min.git

2. Get the podman image:

a. Get the podman image from docker hub:

    cd ~/projects/podman-slurm-min
    podman --root=/local/$USER/podman pull docker.io/lukro2011/min:1

b. Alternatively, you can build the docker image yourself using podman:

    cd ~/projects/podman-slurm-min
    podman --root=/local/$USER/podman pull docker.io/anibali/pytorch:2.0.1-cuda11.8-ubuntu22.04
    podman --root=/local/$USER/podman build --tag min:1 -f ./Dockerfile .

=== With Slurm

1. Create a tar file containing the docker image:

    cd /scratch/$USER/
    podman --root=/local/$USER/podman save min:1 > min1.tar

2. Copy the run_podman_container.sh script to the directory containing the tar file after replacing TODO@fim.uni-passau.de with your email address:

    cd ~/projects/podman-slurm-min
    cp run_podman_container.sh /scratch/$USER/

3. Submit the job to slurm:

    cd /scratch/$USER/
    sbatch run_podman_container.sh

4. Check the status of the job:

    scontrol show job JOBID

5. Once the job is complete, check the output:

    cat slurm-JOBID.out

=== Without Slurm

Run the following command:

    podman run --rm --name "min-container" "localhost/min:1" python src/main.py


